2024-10-28 22:34:27,301 ┆ ⛔ ┆ WARNING ┆ ⛔ ┆ Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "F:\PythonProject\module11_12_13_14\module_12\module_12_4\tests_12_4.py", line 25, in test_run
    n1 = cd.Runner(15)
         ^^^^^^^^^^^^^
  File "F:\PythonProject\module11_12_13_14\module_12\module_12_4\code.py", line 7, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2024-10-28 22:34:27,302 ┆ ⛔ ┆ WARNING ┆ ⛔ ┆ Неверная скорость для Runner
Traceback (most recent call last):
  File "F:\PythonProject\module11_12_13_14\module_12\module_12_4\tests_12_4.py", line 15, in test_walk
    n = cd.Runner("test_name", -2)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\PythonProject\module11_12_13_14\module_12\module_12_4\code.py", line 12, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -2
